version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo18-db
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo-net

  odoo:
    image: odoo:18.0
    container_name: odoo18
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
      DATABASE: odoo
    volumes:
      - odoo-data:/var/lib/odoo
    networks:
      - odoo-net

  django:
    container_name: defcon-ecommerce-api
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_DB_NAME=odoo
      - DJANGO_DB_USER=odoo
      - DJANGO_DB_PASSWORD=odoo
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
    ports:
      - "8000:8000"
    networks:
      - odoo-net

volumes:
  odoo-db-data:
  odoo-data:

networks:
  odoo-net:
    driver: bridge
