version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      # TZ: Asia/Kolkata
      # POSTGRES_INITDB_ARGS: "--timezone=Asia/Kolkata"
      # PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo-net

  odoo:
    build:
      context: .
      dockerfile: odooDockerfile
    container_name: odoo18
    depends_on:
      - db
    ports:
      - "8099:8069"
    environment:
      # HOST: 89.116.20.12
      HOST: db
      USER: odoo
      PASSWORD: odoo
      DATABASE: odoo
      MASTER_PASSWORD: odoo
    volumes:
      # - odoo-data:/var/lib/odoo
      - ./odoo-data:/var/lib/odoo
      - ./backup:/backup
    networks:
      - odoo-net

  django:
    container_name: defcon-ecommerce-api
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             gunicorn defcon_ecommerce.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_NAME=zainab
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    networks:
      - odoo-net

volumes:
  odoo-db-data:
  odoo-data:

networks:
  odoo-net:
    driver: bridge
